DROP TABLE IF EXISTS device;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS scene;
DROP TABLE IF EXISTS scene_action;

CREATE TABLE device (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deviceType INTEGER NOT NULL,
  deviceName TEXT NOT NULL,
  deviceAddress TEXT UNIQUE NOT NULL,
  deviceRoom TEXT NOT NULL,
  deviceStatus TEXT,
  is_registered INTEGER
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


CREATE TABLE scene (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sceneName TEXT UNIQUE NOT NULL,
  sceneBackground TEXT NOT NULL
);

CREATE TABLE scene_action (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  actionDevice TEXT NOT NULL,
  actionRoom TEXT NOT NULL,
  action TEXT,
  scene_id INTEGER,
  FOREIGN KEY (scene_id) REFERENCES scene (id)
);
